runs: 
  #Start arrangement with 0 becasue the first one gets thrown out
  arrangements: [0,10,20,30,40,45,50,60,70,80,88] 
  #arrangements: [0,45,90] 
  num_reps: 10
  save_path: "/home/ranstlouis/Documents/data/cycle_data.csv"