# Top-level settings
settings:
    traj_type: 'interp'  # Types include: 'waveform', 'interp', 'direct'


# Place all of the type-specific settings in here
config:
    interp_type: 'linear'
    subsample_num: 90 #Total number of subsamples
    num_cycles: 2
    setpoints:
        # [time, finger1, finger2, n/c, n/c]
        main:
            - [ 0.0,   0,0,   0,0,   0,0,     0,0 ]
            - [ 1.0,   0,0,   0,0,   0,0,     0,0 ]
            - [ 2.0,   15,0,   15,0,   15,0,     15,0]
            - [ 3.0,   15,0,   15,0,   15,0,     15,0]
            - [ 4.0,   15,0,   15,0,   15,0,     15,0]
            - [ 5.0,   15,0,   15,0,   15,0,     15,0]
            - [ 6.0,   15,0,   15,0,   15,0,     15,0]
            - [ 7.0,   15,0,   15,0,   15,0,     15,0]
            - [ 8.0,   0,0,   0,0,   0,0,     0,0 ]
            - [ 9.0,   0,0,   0,0,   0,0,     0,0 ]

        
