# Top-level settings
settings:
    traj_type: 'interp'  # Types include: 'waveform', 'interp', 'direct'


# Place all of the type-specific settings in here
config:
    interp_type: 'linear'
    subsample_num: 90 #Total number of subsamples
    num_cycles: 2
    setpoints:
        # [time, finger1, finger2, n/c, n/c]
        main:
            - [ 0.0,   0,0,   0,0,   0,0,     0,0 ]
            - [ 1.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ]
            - [ 2.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ] 
            - [ 3.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ]                 
            - [ 4.0,   15,15,   15,15,   15,15,     15,15]
            - [ 5.0,   15,15,   15,15,   15,15,     15,15]
            - [ 6.0,   15,15,   15,15,   15,15,     15,15]
            - [ 7.0,   15,15,   15,15,   15,15,     15,15]
            - [ 8.0,   15,15,   15,15,   15,15,     15,15]
            - [ 9.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ]
            - [ 10.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ]
            - [ 11.0,   -5,-5,   -5,-5,   -5,-5,     -5,-5 ]
            - [ 12.0,   0,0,   0,0,   0,0,     0,0 ]

        
