# Top-level settings
settings:
    traj_type: 'direct'  # Types include: 'waveform', 'interp', 'direct'


# Place all of the type-specific settings in here
config:
    interp_type: 'linear'
    setpoints:
        # [time, finger1, finger2, n/c, n/c]
        main:            
            - [ 0.0,   15,15,   15,15,   15,15,  15,15]
            - [ 1.0,   -5,-5,   -5,-5,   -5,-5, -5,-5 ]
            - [ 2.0,   -5,-5,   -5,-5,   -5,-5, -5,-5 ]
            

        
