# Top-level settings
settings:
    traj_type: 'interp'  # Types include: 'waveform', 'interp', 'direct'


# Place all of the type-specific settings in here
config:
    interp_type: 'linear'
    subsample_num: 90 #Total number of subsamples
    num_cycles: 2
    setpoints:
        # [time, finger1, finger2, n/c, n/c]
        main:
            - [ 0.0,   0,0,   0,0,   0,0,     0,0 ]
            - [ 1.0,   -10,-10,   -10,-10,   -10,-10, -10,-10 ]
            - [ 2.0,   -10,-10,   -10,-10,   -10,-10, -10,-10 ] 
            - [ 3.0,   -10,-10,   -10,-10,   -10,-10, -10,-10 ]                 
            - [ 4.0,   15,15,   15,15,   15,15,     15,15]
            - [ 5.0,   15,15,   15,15,   15,15,     15,15]
            

        
