items:
# # Dictionary matching each April tag to an arrangement value
#
# ## General remarks#
#
# - name is optional
# - height represents centroid in meters
#
# ### Syntax
#
# items:
#   {
#     'TAG_ID':{name: ITEM_NAME, arrange: ARRANGEMENT_VALUE, height: HEIGHT/2},
#     ...
#   }

  items:  
    {'19': {name: test1, arrange: 5,  height: 0.01}, 
     '20': {name: test2, arrange: 5,  height: 0.0275},
     '21': {name: test3, arrange: 80,  height: 0.11},
     '22': {name: test4, arrange: 0,  height: 0.04},
     '23': {name: test5, arrange: 0,  height: 0.032},
     '12': {name: test6, arrange: 0,  height: 0.04},
     '13': {name: test6, arrange: 0, height: 0.045},
     '14': {name: test6, arrange: 85, height: 0.0225},
   }

  
