items:
# # Dictionary matching each April tag to an arrangement value
#
# ## General remarks#
#
# - name is optional
#
# ### Syntax
#
# items:
#   {
#     'TAG_ID':{name: ITEM_NAME, arrange: ARRANGEMENT_VALUE},
#     ...
#   }

  items:  
    {'19': {name: test1, arrange: 90,  height: 0.02}, 
     '20': {name: test2, arrange: 20,  height: 0.02},
     '21': {name: test3, arrange: 45,  height: 0.02},
     '22': {name: test4, arrange: 80,  height: 0.02},
     '23': {name: test5, arrange: 0,  height: 0.02},
     '12': {name: test6, arrange: 0,  height: 0.02},
     '13': {name: test6, arrange: 0, height: 0.02},
     '14': {name: test6, arrange: 85, height: 0.04},
   }

  
